[2.602s] Invoking command in '/home/akariros/Akari_ros2_humble/py_akari_pubsub': PYTHONPATH=/home/akariros/Akari_ros2_humble/build/py_akari_pubsub/prefix_override:/home/akariros/Akari_ros2_humble/install/py_akari_pubsub/lib/python3.10/site-packages:${PYTHONPATH} /usr/bin/python3 setup.py egg_info --egg-base ../build/py_akari_pubsub build --build-base /home/akariros/Akari_ros2_humble/build/py_akari_pubsub/build install --record /home/akariros/Akari_ros2_humble/build/py_akari_pubsub/install.log --single-version-externally-managed
[3.137s] Traceback (most recent call last):
[3.137s]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2866, in get_entry_map
[3.142s]     ep_map = self._ep_map
[3.142s]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2828, in __getattr__
[3.143s]     raise AttributeError(attr)
[3.143s] AttributeError: _ep_map. Did you mean: '_dep_map'?
[3.144s] 
[3.144s] During handling of the above exception, another exception occurred:
[3.144s] 
[3.144s] Traceback (most recent call last):
[3.145s]   File "/home/akariros/Akari_ros2_humble/py_akari_pubsub/setup.py", line 5, in <module>
[3.145s]     setup(
[3.145s]   File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 152, in setup
[3.145s]     _install_setup_requires(attrs)
[3.145s]   File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 142, in _install_setup_requires
[3.145s]     dist = MinimalDistribution(attrs)
[3.146s]   File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 134, in __init__
[3.146s]     distutils.core.Distribution.__init__(self, filtered)
[3.146s]   File "/usr/lib/python3/dist-packages/setuptools/dist.py", line 457, in __init__
[3.146s]     for ep in pkg_resources.iter_entry_points('distutils.setup_keywords'):
[3.146s]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 646, in <genexpr>
[3.146s]     for entry in dist.get_entry_map(group).values()
[3.147s]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2868, in get_entry_map
[3.147s]     ep_map = self._ep_map = EntryPoint.parse_map(
[3.147s]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2549, in parse_map
[3.148s]     for group, lines in data:
[3.148s]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 3205, in split_sections
[3.149s]     for line in yield_lines(s):
[3.149s]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 2780, in _get_metadata
[3.150s]     for line in self.get_metadata_lines(name):
[3.150s]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1422, in get_metadata_lines
[3.150s]     return yield_lines(self.get_metadata(name))
[3.150s]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1412, in get_metadata
[3.151s]     value = self._get(path)
[3.151s]   File "/usr/lib/python3/dist-packages/pkg_resources/__init__.py", line 1616, in _get
[3.151s]     with open(path, 'rb') as stream:
[3.151s] FileNotFoundError: [Errno 2] No such file or directory: '/home/akariros/Akari_ros2_humble/install/m5displayserver/lib/python3.10/site-packages/m5displayserver-0.0.0-py3.10.egg-info/entry_points.txt'
[3.192s] Invoked command in '/home/akariros/Akari_ros2_humble/py_akari_pubsub' returned '1': PYTHONPATH=/home/akariros/Akari_ros2_humble/build/py_akari_pubsub/prefix_override:/home/akariros/Akari_ros2_humble/install/py_akari_pubsub/lib/python3.10/site-packages:${PYTHONPATH} /usr/bin/python3 setup.py egg_info --egg-base ../build/py_akari_pubsub build --build-base /home/akariros/Akari_ros2_humble/build/py_akari_pubsub/build install --record /home/akariros/Akari_ros2_humble/build/py_akari_pubsub/install.log --single-version-externally-managed
